apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   name: mongo-order
 name: mongo-order-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: mongo-order
       component-type: db
   spec:
     containers:
     - image: asia.gcr.io/fxprcs/fxprcs-mongo-order:v1
       name: mongo-order
       ports:
       - name: mongo-order
         containerPort: 27017
         hostPort: 27017
       volumeMounts:
           - name: mongo-order-persistent-storage
             mountPath: /data/db
     volumes:
       - name: mongo-order-persistent-storage
         gcePersistentDisk:
           pdName: mongo-order-disk
           fsType: ext4
