apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   name: mongo-main
 name: mongo-main-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: mongo-main
       component-type: db
   spec:
     containers:
     - image: asia.gcr.io/fxprcs/fxprcs-mongo-main:v1
       name: mongo-main
       ports:
       - name: mongo-main
         containerPort: 27017
         hostPort: 27017
       volumeMounts:
           - name: mongo-main-persistent-storage
             mountPath: /data/db
     volumes:
       - name: mongo-main-persistent-storage
         gcePersistentDisk:
           pdName: mongo-main-disk
           fsType: ext4
