apiVersion: v1
kind: Service
metadata:
 name: web-order
 labels:
   name: web-order
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 3002
     protocol: TCP
 selector:
   name: web-order
