apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   name: web-order
 name: web-order-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: web-order
       component-type: web-server
   spec:
     containers:
     - image: 921141745046.dkr.ecr.us-west-2.amazonaws.com/cpa/aml_fxprcs-node-order:v3
       name: web-order
       ports:
       - containerPort: 3000
         name: http-server
       env:
        - name: AWS_SECRET_ACCESS_KEYID
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: accesskeyid
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-keys
              key: secretaccesskey
