apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   name: web-order
 name: web-order-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: web-order
       component-type: web-server
   spec:
     containers:
     - image: asia.gcr.io/fxprcs/fxprcs-node-order:v8
       name: web-order
       ports:
       - containerPort: 3000
         name: http-server
