apiVersion: v1
kind: Service
metadata:
 name: web-main
 labels:
   name: web-main
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 3000
     protocol: TCP
 selector:
   name: web-main
