apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   name: mongo-main
 name: mongo-main-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: mongo-main
       component-type: db
   spec:
     containers:
     - image: 921141745046.dkr.ecr.us-west-2.amazonaws.com/cpa/aml_fxprcs-mongo-main:v1
       name: mongo-main
       ports:
       - name: mongo-main
         containerPort: 27017
         hostPort: 27017
       volumeMounts:
           - name: mongo-main-persistent-storage
             mountPath: /data/db
     volumes:
       - name: mongo-main-persistent-storage
         awsElasticBlockStore:
           volumeID: vol-04d498075234f0cdc
           fsType: ext4
     nodeSelector:
         failure-domain.beta.kubernetes.io/zone: ap-southeast-1a
